name = "hunger-game-api"
main = "workers/api.js"
compatibility_date = "2024-12-30"

# 환경 변수 (개발용)
[vars]
ENVIRONMENT = "development"

# 프로덕션 환경 설정
[env.production]
name = "hunger-game-api"

[env.production.vars]
ENVIRONMENT = "production"

# API 키는 보안을 위해 secrets로 관리합니다
# 개발 환경 설정:
# wrangler secret put NAVER_CLIENT_ID
# wrangler secret put NAVER_CLIENT_SECRET
#
# 프로덕션 환경 설정:
# wrangler secret put NAVER_CLIENT_ID --env production
# wrangler secret put NAVER_CLIENT_SECRET --env production 