name = "hunger-game"
compatibility_date = "2024-01-01"
main = "workers/api.js"

# 정적 파일 설정
[assets]
directory = "."
binding = "ASSETS"

# 환경 변수 설정 (실제 값은 wrangler secret put 명령어로 설정)
[env.production.vars]
ENVIRONMENT = "production"
NAVER_CLIENT_ID = "udDZDimZnb4Z3twN1KGI"
NAVER_CLIENT_SECRET = "p6iNP2KEmb"

# 정적 파일 서빙을 위한 설정
[[env.production.rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js"]
fallthrough = true

# 개발 환경 설정
[env.development]
vars = { ENVIRONMENT = "development", NAVER_CLIENT_ID = "udDZDimZnb4Z3twN1KGI", NAVER_CLIENT_SECRET = "p6iNP2KEmb" }

# Workers Routes 설정 (선택사항)
# route = "your-domain.com/*"

# KV 네임스페이스 (게임 세션 저장용, 선택사항)
# [[kv_namespaces]]
# binding = "GAME_SESSIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 데이터베이스 (선택사항)
# [[d1_databases]]
# binding = "DB"
# database_name = "hunger-game-db"
# database_id = "your-database-id" 